### ISSUE TITLE
Possible project renaming

### ISSUE THREAD

**Issue by arctic-hen7** [arctic-hen7/perseus#1]
This project was originally named Perseus because of the inspiration as an extension of Percy, but Sycamore turned out to be much better for the job, and 'Sycamoreus' didn't quite flow off the tongue, so I stuck with Perseus.

The beta version of this project is now ready, but before I publish it, I want to decide on a name for the project for now. This is a tracking issue for that.

**Comment by arctic-hen7** [comment]
Here are my thoughts at the moment:

- Perseus (just stick with current)
- Odysseus (maybe a little difficult to quickly type...)
- Heracles (Greek version of Hercules, but Hercules is already a crate...)

I'm certainly thinking in the vein of Ancient Greek heroes for this project...

**Comment by arctic-hen7** [comment]
Also Ulysses, that's unclaimed.

**Comment by arctic-hen7** [comment]
Okay, I'm going to keep Perseus for at least v0.1.0, but I'll leave this issue open for tracking possible name changes in future.

**Comment by lukechu10** [comment]
I personally quite like the name perseus.

Also @arctic-hen7 are you on the Sycamore discord server? I could add a new channel for perseus there if you want.

**Comment by arctic-hen7** [comment]
Yeah so do to be honest!

**Comment by arctic-hen7** [comment]
I'm not, but that'd be great! Thanks!

**Comment by arctic-hen7** [comment]
@lukechu10 I've invited you to the [Perseus Gitter community](https://gitter.im/perseus-framework/community) to discuss that over there.

**Comment by arctic-hen7** [comment]
Well, the project seems to be going quite well with its current name, so I think this can be safely closed!
