### ISSUE TITLE
Missing WebAssembly link in the hello-world doc

### ISSUE THREAD

**Issue by Mazwak** [arctic-hen7/perseus#113]
https://github.com/arctic-hen7/perseus/blob/73a1f0cb0e1d9dba05d929b279f9a511b14797d7/docs/next/en-US/hello-world.md?plain=1#L73

**Comment by arctic-hen7** [comment]
Ah, thanks for catching this!

**Comment by arctic-hen7** [comment]
Actually @Mazwak do you want to open a quick PR for this?

**Comment by Mazwak** [comment]
I can make a PR. I’m not very fluent with git and github, so I might do it badly first.

Is the link https://webassembly.org/ that you forgot ?

**Comment by arctic-hen7** [comment]
Yeah, that's the one. There's a reasonable guide in the `CONTRIBUTING.md` file at the root of this repo that can walk you through the basics.
