### ISSUE TITLE
Error: `unwrap_throw` failed and assertion failed: `(left == right)`

### ISSUE THREAD

**Issue by tqwewe** [arctic-hen7/perseus#114]
**Describe the bug**
Errors are shown in the console and the app fails to render.

**To Reproduce**
To reproduce is very strange, the best I could do is just create a github repo showing the error occuring.
https://github.com/tqwewe/perseus-error-repro

Clone the repo and run `perseus serve`.

**Expected behavior**
The app should render correctly with no errors. It seems to work with Sycamore without Perseus.

**Environment (please complete the following information):**
 - Perseus Version: 0.3.2
 - Sycamore Version: 0.7.1
 - OS: OSX
 - Browser: chrome

**Additional context**
Try changing/deleting any of the code in the view at https://github.com/tqwewe/perseus-error-repro/blob/main/src/sidebar.rs#L8, and you'll see a different error of assertion failed: `(left == right)`. This bug is very strange. I tried `cargo clean && perseus clean`, but that didn't seem to do anything.

**Comment by arctic-hen7** [comment]
I don't think there's a single `unwrap_throw()` in the whole of Perseus from memory, so this sounds like its coming from Sycamore. That said, it could well be something wrong with Perseus. Does anything change if you disable hydration?

**Comment by tqwewe** [comment]
> Does anything change if you disable hydration?

Yep! Removing the hydration feature flag makes the errors go away, and adding it back makes the errors show again.

**Comment by arctic-hen7** [comment]
Okay, this actually might explain some of the errors I was having with hydration and the Perseus website then, thanks! I'll close this here because it's not a Perseus issue, but if you could spin up an MRE that uses `render_to_string` and `hydrate_to` and open a Sycamore issue, that'd be great!

**Comment by arctic-hen7** [comment]
As for your app, I'd recommend ditching the `hydrate` flag for now, you won't see any significant performance hits at all unless people try to scroll within the first few milliseconds of your app loading (they'll be thrown back to the top momentarily).

**Comment by tqwewe** [comment]
Okay perfect thanks so much! I'm still new to sycamore, but I'll try to open an issue there soon.

**Comment by arctic-hen7** [comment]
No problem. Happy to help with the MRE if you want!
