### ISSUE TITLE
Local state freezing in development

### ISSUE THREAD

**Issue by arctic-hen7** [arctic-hen7/perseus#121]
This issue is requesting an enhancement to Perseus. Details of the scope will be available in issue labels.
The user described the problem related to this request as follows:
> Currently, developing Perseus apps can be irritating because you always lose your place. This is the problem HMR was designed to solve in the JS ecosystem, though it's widely accepted that this is basically impossible in the Wasm ecosystem until code-splitting and the like can be used without thousands of lines of glue code.

The user described the issue as follows:
> With state freezing though, Perseus can support something even better than HMR, it can freeze the entire app's state and store it in `IndexedDB` or the like, allowing developers to keep their place even between full restarts of their computers. This is a nifty idea, but there is one problem. There will inevitably be cases in which something gets corrupted and the user wants to start afresh. We can support that by simply clearing the stored state and reloading the page, but we'll need some kind of button to let the user do this. From memory NextJS has a little state indicator that pops out of the side of the screen when you move your mouse near it, which could be quite good. Of course, all this would only be supported when the `freeze` feature is enabled, and only in development.
- The author is willing to attempt an implementation: true 

<details>
<summary>Tribble internal data</summary>

dHJpYmJsZS1yZXBvcnRlZCxDLWVuaGFuY2VtZW50LGF1dGhvci13aWxsaW5nLXRvLWltcGw=

</details>

**Comment by lukechu10** [comment]
It would be nice if this functionality could ultimately be built into sycamore itself because it sounds like sycamore apps not using perseus could benefit as well.

**Comment by arctic-hen7** [comment]
Oh yeah that would be fantastic! The issue is that it requires a global state system, which Sycamore doesn't prescribe (and probably shouldn't). That said, it should be fairly easy to do if there were one, and I could build it as a separate library for caching a given `struct` to `IndexedDB` and fetching it out. That would make it as easy as possible to integrate into Sycamore in future as possible.

**Comment by arctic-hen7** [comment]
HSR (Hot State Reloading) is now implemented!

**Comment by arctic-hen7** [comment]
I've also eliminated the need for a little indicator by making the stored state simply clear itself after a CLi-initiated reload, which means the user can return to the original state by simply reloading, which is consistent with typical HMR behavior. This also avoids keeping old state for the next load when the user terminates the CLI process (the state from the last CLI-induced reload would be brought back up even several days later).
