### ISSUE TITLE
Add `perseus new` and `perseus init` to CLI

### ISSUE THREAD

**Issue by lukechu10** [arctic-hen7/perseus#128]
This issue is requesting an enhancement to Perseus. Details of the scope will be available in issue labels.
The user described the problem related to this request as follows:
> Add `perseus new` and `perseus init` commands to the cli for easy quick start.

The user described the issue as follows:
> The `perseus new <project_name>` command, just like `cargo new`, should create a new minimal perseus app under the specified directory. The `perseus init` feature, in parallel with `cargo init`, should initialize the same minimal perseus app in the current existing directory.

There should also be flags for specifying VCS and eventually other options.

Unanswered questions:
- Should the cli pull the new project template from a git repository or should it be hard coded into the cli? Choosing the former would allow maximum flexibility and tweaking the template without pulling a new `perseus-cli` release. Choosing the later would make sure that the CLI initializes a project that corresponds to the CLI version, although that might not always be wanted.
- The author is willing to attempt an implementation: false 

<details>
<summary>Tribble internal data</summary>

dHJpYmJsZS1yZXBvcnRlZCxDLWVuaGFuY2VtZW50

</details>

**Comment by arctic-hen7** [comment]
I think this is a great idea, and I prefer pulling from a repo, but we can use branches to control the versioning. The user could also easily specify an alternative repo template that way, which would be very useful in the long term, I think.
