### ISSUE TITLE
Add Axum integration

### ISSUE THREAD

**Issue by jingslunt** [arctic-hen7/perseus#133]
This issue is requesting an enhancement to Perseus. Details of the scope will be available in issue labels.
The user described the problem related to this request as follows:
> Amazing job, this can be combined with auxm to make a Fullstack Framework。
MoonZoon is based on Actix ,we prefer axum to actix.

The user described the issue as follows:
> Amazing job, this can be combined with auxm to make a Fullstack Framework。
MoonZoon is based on Actix ,we prefer axum to actix.
- The author is willing to attempt an implementation: false 

<details>
<summary>Tribble internal data</summary>

dHJpYmJsZS1yZXBvcnRlZCxDLWVuaGFuY2VtZW50

</details>

**Comment by arctic-hen7** [comment]
Perseus is already a fullstack framework, so I assume you're asking for an Axum integration? If so, I would be very happy to implement that for v0.3.5!

**Comment by arctic-hen7** [comment]
This is now complete and all tests pass on the new integration! This probably won't be of great use to anyone just yet, unless you want to play with the internals of Perseus using the Axum integration. In the coming beta versions though, I'll introduce a system for users to add custom API routes, at which time the integration will probably become extremely useful!
