### ISSUE TITLE
Not Found: ./dist/render_conf.json

### ISSUE THREAD

**Issue by afidegnum** [arctic-hen7/perseus#134]
This issue is reporting a bug in the code of Perseus. Details of the scope will be available in issue labels.
The author described their issue as follows:
> $~/Rustjr/myblog$ perseus snoop serve
   Compiling myblog v0.1.0 ~/Rustjr/myblog)
   Compiling perseus-engine v0.3.5 (/home/base/Rustjr/myblog/.perseus)
   Compiling perseus-engine-server v0.3.5 (/home/base/Rustjr/myblog/.perseus/server)
    Finished dev [unoptimized + debuginfo] target(s) in 54.63s
     Running `target/debug/perseus-engine-server`
thread 'main' panicked at 'Couldn't get render configuration!: StoreError(ReadFailed { name: "./dist/render_conf.json", source: Os { code: 2, kind: NotFound, message: "No such file or directory" } })', /home/base/.cargo/registry/src/github.com-1ecc6299db9ec823/perseus-0.3.5/src/init.rs:360:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

The steps to reproduce this issue are as follows:
> perseus snoop serve

A minimum reproducible example is available at <>.
- Hydration-related: false
- The author is willing to attempt a fix: false 

<details>
<summary>Tribble internal data</summary>

dHJpYmJsZS1yZXBvcnRlZCxDLWJ1ZyxBLWNsaQ==

</details>

**Comment by afidegnum** [comment]
The problem happens when called `perseus serve` with the snoop argument. otherwise normal `serve` works correctly

**Comment by arctic-hen7** [comment]
Does this persist after `perseus clean`?

**Comment by arctic-hen7** [comment]
Ah, yes you do! `perseus snoop serve` must be preceded by `perseus build` if you haven't already run it.

**Comment by afidegnum** [comment]
Ok, Thanks,
