### ISSUE TITLE
Authentication Example doesn't work with hydration

### ISSUE THREAD

**Issue by adundovi** [arctic-hen7/perseus#135]
This issue is reporting a bug in the code of Perseus. Details of the scope will be available in issue labels.
The author described their issue as follows:
> Authentication Example doesn't work as expected with hydration persent. The login form is not displayed correctly (the input field is missing). It is displayed when pressing first "Login" and "Logout".

The steps to reproduce this issue are as follows:
> Just run the following example with hydration turned on:
https://github.com/arctic-hen7/perseus/tree/main/examples/demos/auth

A minimum reproducible example is available at <>.
- Hydration-related: true
- The author is willing to attempt a fix: true 

<details>
<summary>Tribble internal data</summary>

dHJpYmJsZS1yZXBvcnRlZCxDLWJ1ZyxBLXRlc3RpbmcsQS1oeWRyYXRpb24sYXV0aG9yLXdpbGxpbmctdG8taW1wbA==

</details>

**Comment by arctic-hen7** [comment]
Yes, I noticed this when I was building it, but I'll add a note to the readme there that it doesn't work with hydration enabled. Thanks for the catch!

As for *why* it doesn't work -- search me! I'm migrating everything over to the new Sycamore reactive primitives at the moment, which should hopefully fix the hydration issues with this, the `plugins` example, and the website (which is broken by hydration as well).

In light of that, I'll probably close this for now, and it might be worth adding a note to the common pitfalls section of the docs about the state of hydration bugs currently.
