### ISSUE TITLE
Type Error on ErrorPages

### ISSUE THREAD

**Issue by afidegnum** [arctic-hen7/perseus#136]
This issue is reporting a bug in the code of Perseus. Details of the scope will be available in issue labels.
The author described their issue as follows:
> A little issue on the `expected_type` on ErrorPages

The steps to reproduce this issue are as follows:
> I have an error of: expected ErrorPages<G>, found ErrorPages<dyn Any> [type-mismatch] error

A minimum reproducible example is available at <https://github.com/arctic-hen7/perseus/blob/main/examples/demos/auth/src/error_pages.rs#L16>.
- Hydration-related: false
- The author is willing to attempt a fix: false 

<details>
<summary>Tribble internal data</summary>

dHJpYmJsZS1yZXBvcnRlZCxDLWJ1Zw==

</details>

**Comment by arctic-hen7** [comment]
This is happening with the authentication example? Are you running it on the `main` branch?

**Comment by afidegnum** [comment]
Hi, sorry for the late reply, 
yes, I'm running it on the main branch. I noticed the issue is coming from RLS. however calling cargo-check everything seems to be fine, but maybe you can check from your side too!

**Comment by lukechu10** [comment]
> yes, I'm running it on the main branch. I noticed the issue is coming from RLS. however calling cargo-check everything seems to be fine, but maybe you can check from your side too!

That sounds like an issue with RLS, not with perseus. Also know that RLS is soft deprecated now. It is recommended to use [rust-analyzer](https://[rust-analyzer](https://rust-analyzer.github.io/).github.io/) instead.

**Comment by afidegnum** [comment]
Thanks, Noted

**Comment by arctic-hen7** [comment]
I might close this then. @afidegnum if there is any issue with Perseus here, please let me know and I'll reopen it.
