### ISSUE TITLE
"Ejecting" Page is blank in the docs

### ISSUE THREAD

**Issue by Me163** [arctic-hen7/perseus#149]
Apologies if docs issues shouldn't be reported here - if so lmk where I should be doing that.

This issue is reporting a bug in the code of Perseus. Details of the scope will be available in issue labels.
The author described their issue as follows:
> "Ejecting" Page is blank in the docs

The steps to reproduce this issue are as follows:
> https://arctic-hen7.github.io/perseus/en-US/docs/ejecting

This page is linked to from https://arctic-hen7.github.io/perseus/en-US/docs/next/reference/server-communication

A minimum reproducible example is available at <>.
- Hydration-related: false
- The author is willing to attempt a fix: false 

<details>
<summary>Tribble internal data</summary>

dHJpYmJsZS1yZXBvcnRlZCxDLWJ1Zw==

</details>

**Comment by arctic-hen7** [comment]
Huh, that's odd. Thanks, I'll fix that! (Probably an error when I released the new version...)

Also yes, this is the right place to report docs errors!
