### ISSUE TITLE
 <!DOCTYPE html> is printed two times.

### ISSUE THREAD

**Issue by afiqzx** [arctic-hen7/perseus#154]
This issue is reporting a bug in the code of Perseus. Details of the scope will be available in issue labels.
The author described their issue as follows:
> &lt;!DOCTYPE html&gt; is printed two times.

The steps to reproduce this issue are as follows:
> 1. Download my repo: https://github.com/afiqzx/afiq_setting
2. build with `perseus serve -w`. (Maybe -w is unneded but I used it when the bug occured)
3. Open the page in your browser.
4. View source, and see `<!DOCTYPE html>` printed two times on top of the document.

A minimum reproducible example is available at <https://github.com/afiqzx/afiq_setting>.
- Hydration-related: false
- The author is willing to attempt a fix: false (actually I will if given some pointers.) 

Perseus version: 0.3.5
Sycamore version: 0.7

<details>
<summary>Tribble internal data</summary>

dHJpYmJsZS1yZXBvcnRlZCxDLWJ1Zw==

</details>

**Comment by afiqzx** [comment]
![double_doctype](https://user-images.githubusercontent.com/46773936/175273196-fd0251dc-bd0c-41bf-be00-46a2e0eba765.png)

Here is an example from my browser.

**Comment by arctic-hen7** [comment]
I'm assuming you mean [this repo](https://github.com/afiqzx/homepager) instead, the one you linked to seems to contain configuration files.

**Comment by afiqzx** [comment]
Thank you for the response!
Understood. I will also test the beta when it comes out.
