### ISSUE TITLE
Add user feedback to deployed project server

### ISSUE THREAD

**Issue by allen-woods** [arctic-hen7/perseus#164]
This issue is requesting an enhancement to Perseus. Details of the scope will be available in issue labels.
The user described the problem related to this request as follows:
> No user feedback is supplied when a server is running.

The user described the issue as follows:
> The server of a deployed project should provide user feedback regarding the status of the server, the value of PERSEUS_HOST and the value of PERSEUS_PORT while it is in use. This could be achieved with a simple `println!` or `format!` macro.
- The author is willing to attempt an implementation: true 

<details>
<summary>Tribble internal data</summary>

dHJpYmJsZS1yZXBvcnRlZCxDLWVuaGFuY2VtZW50LGF1dGhvci13aWxsaW5nLXRvLWltcGw=

</details>

**Comment by arctic-hen7** [comment]
Perfectly reasonable! It's worth noting that a deployed server binary will automatically print full errors as well if they occur. I'll get on this in the next few days.
