### ISSUE TITLE
wasm_bindgen failed to resolve on macOS 13.0 m1 chip

### ISSUE THREAD

**Issue by AndyJado** [arctic-hen7/perseus#165]
This issue is reporting a bug in the code of Perseus. Details of the scope will be available in issue labels.
The author described their issue as follows:
> [2/4] 🏗️  Building your app to Wasm...❌

error[E0433]: failed to resolve: use of undeclared crate or module `wasm_bindgen`

The steps to reproduce this issue are as follows:
> MacOS 13, latest version
cargo install perseus-cli --version 0.4.0-beta.5
perseus new my-app
cd my-app/
perseus serve -w

A minimum reproducible example is available at <>.
- Hydration-related: false
- The author is willing to attempt a fix: false 

<details>
<summary>Tribble internal data</summary>

dHJpYmJsZS1yZXBvcnRlZCxDLWJ1ZyxBLWNsaQ==

</details>

**Comment by arctic-hen7** [comment]
Could you post the full output of `perseus snoop wasm-build` please?

**Comment by AndyJado** [comment]
It is fixed by updating the dependency in `Cargo.toml` found here:

https://arctic-hen7.github.io/perseus/en-US/docs/next/tutorials/second-app

and here is snoop:


```
 Compiling my-issue v0.1.0 (/Users/andyjado/Taste/my-issue)
error[E0433]: failed to resolve: use of undeclared crate or module `wasm_bindgen`
 --> src/main.rs:5:1
  |
5 | #[perseus::main(perseus_warp::dflt_server)]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ use of undeclared crate or module `wasm_bindgen`
  |
  = note: this error originates in the attribute macro `perseus::main` (in Nightly builds, run with -Z macro-backtrace for more info)

warning: unused import: `SsrNode`
 --> src/templates/index.rs:2:44
  |
2 | use sycamore::prelude::{view, Html, Scope, SsrNode, View};
  |                                            ^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

For more information about this error, try `rustc --explain E0433`.
warning: `my-issue` (bin "my-issue") generated 1 warning
error: could not compile `my-issue` due to previous error; 1 warning emitted
➜  my-issue 
```

**Comment by arctic-hen7** [comment]
So this is not actually a bug?

**Comment by AndyJado** [comment]
- This is how `perseus new my-app` appears following instruments in the Readme QuickStart. `wasm-bindgen` don't resolve.
```
[dependencies]
perseus = { version = "=0.4.0-beta.3", features = [ "hydrate" ] }
sycamore = "=0.8.0-beta.5"
serde = { version = "1", features = [ "derive" ] }
serde_json = "1"
```

- Now it works by:

```
perseus = { version = "=0.4.0-beta.5", features = [ "hydrate" ] }
sycamore = "=0.8.0-beta.7"
```
