### ISSUE TITLE
Unable to build CLI (0.3.5)

### ISSUE THREAD

**Issue by orhun** [arctic-hen7/perseus#166]
This issue is reporting a bug in the code of Perseus. Details of the scope will be available in issue labels.
The author described their issue as follows:
> I'm getting the following error while building: 

```
error: failed to run custom build command for `perseus-cli v0.3.5 (/build/perseus-cli/src/perseus-0.3.5/packages/perseus-cli)`

Caused by:
  process didn't exit successfully: `/build/perseus-cli/src/perseus-0.3.5/target/release/build/perseus-cli-c4decf72c513eabe/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-changed=../../examples/core/basic/.perseus

  --- stderr
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', packages/perseus-cli/build.rs:35:52
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
```

The steps to reproduce this issue are as follows:
> Cloning the repository, check out to tag 0.3.5, run `cargo build`.

A minimum reproducible example is available at <>.
- Hydration-related: false
- The author is willing to attempt a fix: true 

<details>
<summary>Tribble internal data</summary>

dHJpYmJsZS1yZXBvcnRlZCxDLWJ1ZyxBLWNsaSxhdXRob3Itd2lsbGluZy10by1pbXBs

</details>

**Comment by arctic-hen7** [comment]
Have you run `bonnie setup`?

**Comment by orhun** [comment]
I just tried running `bonnie setup` before building CLI and got this:

```
61 verbose stack Error: ENOENT: no such file or directory, open '/build/perseus-cli/src/perseus-0.3.5/packages/perseus-cli/website/package.json'
62 verbose cwd /build/perseus-cli/src/perseus-0.3.5/packages/perseus-cli
63 verbose Linux 5.18.12-arch1-1
64 verbose node v18.6.0
65 verbose npm  v8.14.0
66 error code ENOENT
67 error syscall open
68 error path /build/perseus-cli/src/perseus-0.3.5/packages/perseus-cli/website/package.json
69 error errno -2
70 error enoent ENOENT: no such file or directory, open '/build/perseus-cli/src/perseus-0.3.5/packages/perseus-cli/website/package.json'
71 error enoent This is related to npm not being able to find a file.
71 error enoent
72 verbose exit -2
```

**Comment by arctic-hen7** [comment]
Okay, that's probably an error in the setup script. I'll review that, but it should've fixed the CLI building anyway. Running `cargo build` in `packages/perseus-cli` should work now.

**Comment by arctic-hen7** [comment]
@orhun is this fixed now?

**Comment by orhun** [comment]
Yes, it builds fine now. I'm not still sure how to run the tests, though.

I created the following AUR packages:
- https://aur.archlinux.org/packages/bonnie
- https://aur.archlinux.org/packages/perseus

**Comment by arctic-hen7** [comment]
Great, thanks so much for the packages! The tests need `geckodriver` or `chromedriver` running in the background, and then `bonnie test` should work. You'll also need `rust-script`, which I don't think is documented yet.

**Comment by orhun** [comment]
I see, I will wait for the documentation for running the tests then. Watching the repo!

I think we can close this.
