### ISSUE TITLE
Add a space after the URL when serve is done

### ISSUE THREAD

**Issue by Mazwak** [arctic-hen7/perseus#24]
**Is your feature request related to a problem? Please describe.**

When perseus serve finishes, the message presents the URL immediately followed by an exclamation mark.
VSCode parses the line and finds the URL but it includes the exclamation.

**Describe the solution you'd like**

Put a space between the URL and the exclamation mark.

**Describe alternatives you've considered**

The URL could be surrounded by brackets or parenthesis or …
The VSCode parser could be improved, but there might be a lot of parser not detecting the URL correctly

**Comment by arctic-hen7** [comment]
Thanks for the report! The easiest thing might even be to just put the URL on a line on its own. Would you be happy with that solution?

**Comment by arctic-hen7** [comment]
Interestingly, I'm pretty certain that there's no case in which a URL could even have an unparsed exclamaation mark in it, so I'll consider taking this up with VS Code as well. That said, and immediate solution is needed, and just surrounding it with angular brackets works quite well.

**Comment by arctic-hen7** [comment]
Hilariously, VS Code's parser works for a full stop (legal in URLs), but not for an exclamation mark (illegal in URLs). Nonetheless, angular brackets are now added, and this will be released with static exporting and HTTP response modification in v0.2.2 this afternoon.

**Comment by Mazwak** [comment]
Thanks for the workaround.
