### ISSUE TITLE
Provide pre-built binaries for `perseus-cli`

### ISSUE THREAD

**Issue by lukechu10** [arctic-hen7/perseus#27]
**Is your feature request related to a problem? Please describe.**
Right now, we need to use `cargo install perseus-cli` which can take quite some time.

**Describe the solution you'd like**
Provide pre-built binaries for `perseus-cli`. Preferably, this should include linux, macOS and windows.

**Additional context**
This could be as simple as uploading artifacts to github releases or just building in CI and uploading artifacts. Eventually, it might be nice as well to have a npm package to make it easier to install.

**Comment by arctic-hen7** [comment]
Agreed! I can use the GitHub Actions from Bonnie, it should be about the same.

**Comment by arctic-hen7** [comment]
I've added the CI workflow for this, so it should now work, but I'll close this only after I've confirmed that after I release v0.2.3.

**Comment by arctic-hen7** [comment]
Okay, after far too many retaggings and a commit history that looks slightly like a bomb went off, this works now!
