### ISSUE TITLE
Document styling pitfalls

### ISSUE THREAD

**Issue by arctic-hen7** [arctic-hen7/perseus#28]
**Is your feature request related to a problem? Please describe.**
Without documentation, full-page layouts (e.g. sticky footers and headers with grid layouts) are almost impossible to achieve in Perseus right now. The issue is Perseus' unique DOM hierarchy that's used to store content, which is currently completely undocumented, which leaves users completely in the dark as to why there's an empty `<div>` taking up 50% of a grid layout.

**Describe the solution you'd like**
Document styling pitfalls.

**Describe alternatives you've considered**

**Additional context**

**Comment by arctic-hen7** [comment]
In a future release, these pitfalls should be minimized as much as possible.

**Comment by lukechu10** [comment]
Would it be possible to eventually remove this div wrapper? I am not really familiar with the codebase yet so I don't know how big of a change that would be.

**Comment by arctic-hen7** [comment]
That'll be possible once Sycamore supports creating a template around an existing DOM element.

**Comment by arctic-hen7** [comment]
One thing that we can do right now though is add a little something to make the server content `<div>` invisible after transfer is done.

**Comment by arctic-hen7** [comment]
Done, releasing v0.2.3 once checks pass (or they might not depending on how `geckodriver`'s day is going).

**Comment by arctic-hen7** [comment]
Okay, somehow I've managed to break i18n and routing with this change, so I'm investigating this...

**Comment by arctic-hen7** [comment]
Fixed, nested contexts seem to be an issue in Sycamore.
