### ISSUE TITLE
`perseus clean` panics at index out of bounds

### ISSUE THREAD

**Issue by arctic-hen7** [arctic-hen7/perseus#29]
**Describe the bug**
Whenever running `perseus clean` without the `--dist` flag, the thread will panic because it uses `[1]` to check if `--dist` is present instead of `.get(0)`.

**To Reproduce**
Run `perseus clean`.

**Expected behavior**
The command should succeed.

**Screenshots**

**Environment (please complete the following information):**
 - Perseus Version: v0.2.3
 - Sycamore Version: [v0.6.1
 - OS: Ubuntu
 - Browser: N/A
 - Browser Version: N/A

**Additional context**

**Comment by arctic-hen7** [comment]
This should be very easy to fix, I'll get on it later today.

**Comment by lukechu10** [comment]
It might be a good idea to eventually use a full-featured cli parser like `structopt` or `clap`. This will reduce boilerplate and improve end-user experience (such as better error messages, auto-complete, auto-generated help). This will also make it much easier to add other flags, sub-commands and options in the future.

**Comment by arctic-hen7** [comment]
Yes, I completely agree, and that is in my todo list.

**Comment by arctic-hen7** [comment]
This is done, and will be released in v0.3.0, potentially along with major architectural changes to the CLI to use `structopt` or `clap`. Until then, the `.perseus/` directory can be manually deleted, and I'll try to get v0.3.0 done by tomorrow.
