### ISSUE TITLE
Examples from 0.3.x included in docs for 0.2.x

### ISSUE THREAD

**Issue by adundovi** [arctic-hen7/perseus#60]
[The second app](https://arctic-hen7.github.io/perseus/en-US/docs/0.2.x/second-app) from (stable) docs does not compile. The reason for it seems like the wrong code snippets are included (those from 0.3.x, not 0.2.x). For example, in the 5th snippet one has `RenderFnResultWithCause` while in the text it is not mentioned at all (I presume `StringResultWithCause` is an old name for it).

**To Reproduce**
1. Follow the tutorial (stable) for the second app
2. c/p the code from the snippets
3. `perseus serve` throws a bunch of errors

**Expected behavior**
I expect that the example compiles as described :-)

**Actual result**
```
error[E0432]: unresolved import `perseus::template::RenderFnResultWithCause`
 --> src/templates/index.rs:3:18
  |
3 |     GenericNode, template::RenderFnResultWithCause, Template,
  |                  ^^^^^^^^^^-----------------------
  |                  |         |
  |                  |         help: a similar name exists in the module: `StringResultWithCause`
  |                  no `RenderFnResultWithCause` in `template`
```
(...)
```
error[E0282]: type annotations needed
  --> src/templates/index.rs:41:5
   |
41 |     Ok(serde_json::to_string(&IndexPageProps {
   |     ^^ cannot infer type for type parameter `E` declared on the enum `Result`

error[E0593]: function is expected to take 1 argument, but it takes 2 arguments
  --> src/templates/index.rs:24:25
   |
24 |         .build_state_fn(Rc::new(get_build_props))
   |                         ^^^^^^^^^^^^^^^^^^^^^^^^ expected function that takes 1 argument
...
40 | pub async fn get_build_props(_path: String, _locale: String) -> RenderFnResultWithCause<String> {
   | ----------------------------------------------------------------------------------------------- takes 2 arguments
   |
   = note: required because of the requirements on the impl of `GetBuildStateFnType` for `fn(std::string::String, std::string::String) -> impl Future {get_build_props}`
   = note: required for the cast to the object type `dyn GetBuildStateFnType`
```

**Environment (please complete the following information):**
 - Perseus Version: v0.2.3
 - Sycamore Version: v0.6.1
 - OS: Linux

**Comment by adundovi** [comment]
Great! I didn't look up how the docs are generated, so I don't have suggestions how to fix it.

**Comment by arctic-hen7** [comment]
For some reason this isn't building correctly. Reopening until I've figured that out.

**Comment by arctic-hen7** [comment]
Okay, this was easily fixed by making the Checkout action copy in the whole Git history with `fetch-depth: 0`, rather than its default behavior of copying in only parts. The website now compiles both locally and on CI, and I believe this issue is resolved!

**Comment by adundovi** [comment]
> Also, I feel I should add to this that saying v0.3.0 would be stabilized today was incorrect (sorry!)...

OK, no problem. At the moment, I'm just experimenting, so switching from v0.2.x to v0.3.0 shouldn't be a problem.

Regarding plugins, if I plan to use `perseus serve` to generate CSS in static via `tailwindcss`, should that fall into the `Type 3` plugins? (sorry for off topic)
