### ISSUE TITLE
Template roots don't render with initial loads for static exporting, sometimes

### ISSUE THREAD

**Issue by arctic-hen7** [arctic-hen7/perseus#73]
**Describe the bug**
Right now, `perseus export` will generate templates that have many pages in a rather strange way (actually quite unintended, just a quirk of the system). Let's say we have a template `docs`, which has a root page and a ton of other subpages. Those subpages will all be exported into a `docs/` folder, which is logical, but the root page won't be at `docs/index.html`, it'll be at `docs.html` (outside `docs/`). Unfortunately, different systems handle this in different ways, though most simply won't find the `/docs` page. Note that the subsequent loads system works fine because the internal Perseus structure is expected to work like this.

**To Reproduce**
1. Go to <https://arctic-hen7.github.io/perseus/en-US/docs/> to see this in production.
or
1. Go to <https://arctic-hen7.github.io/perseus> and click on the *Docs* link, which will work.

**Expected behavior**
Template roots should be rendered in the template's folder as `index.html` for the initial loads system, and such pages should be able to be rendered.

**Screenshots**

**Environment (please complete the following information):**
 - Perseus Version: v0.3.0-beta.17 (affects all versions since exporting was introduced though)
 - Sycamore Version: v0.6
 - OS: Ubuntu
 - Browser: Firefox
 - Browser Version:93

**Additional context**

**Comment by afidegnum** [comment]
i'm facing the same issue, but not with export. i.e links placed in index.html do not render unless i manually specify them in `.head()`

**Comment by arctic-hen7** [comment]
That's a very different issue I think. Here, I'm just talking about some pages not rendering properly when exported.

**Comment by afidegnum** [comment]
ok

**Comment by arctic-hen7** [comment]
I've fixed this by placing all initial load pages into their own directories when exporting. That shouldn't result in any changes to the vast majority of codebases, and this should improve compatibility with a wider variety of hosting systems.
