### ISSUE TITLE
Parsing Youtube video script or network error?

### ISSUE THREAD

**Issue by afidegnum** [arctic-hen7/perseus#75]
Perseus is going into the mainstream, while I'm impatient to use it in production, I managed to build a production-ready application. 

**Describe the bug**
I was able to load the Youtube video script but not able to play it. I can't figure out what's blocking it. 

**Expected behavior**
It's a Background video which should be played, I have already tried on the local template which works perfectly. 

**Screenshots**
https://github.com/afidegnum/frontend/blob/main/src/templates/index.rs#L17-L54

**Comment by arctic-hen7** [comment]
Sorry, I don't completely understand how anything in that file is actually supposed to play the video. I assume some imported script is supposed to do something with this, so is the issue that a script isn't being imported? In that case, do you think you could get this down to a *minimum* reproducible example? It's quite difficult for me to debug your larger codebase...

Also, what do you mean when you say it works on the local template?

**Comment by afidegnum** [comment]
ok, thanks, let me rework on it

**Comment by arctic-hen7** [comment]
@afidegnum are you still having this issue?

**Comment by afidegnum** [comment]
sorry for the late reply, 

The issue is not yet resolved. I'm trying to diagnose it while trying the CSS approach too... with the JS approach, the video is being embedded using an iframe taken from this library: https://github.com/pupunzi/jquery.mb.YTPlayer

I'm still trying other alternatives that will not require the use of this library, hopefully, today or tomorrow. 

Thanks a lot for your assistance.

**Comment by arctic-hen7** [comment]
If it's being embedded in an `iframe`, then I don't think that could be a Perseus problem. Sycamore maybe, but it's very possibly something else entirely.

**Comment by arctic-hen7** [comment]
@afidegnum do you think this is a Perseus problem? If not, I think we can close this issue.

**Comment by afidegnum** [comment]
You can close it for now but in case of anything, I will be back to it again.
