### ISSUE TITLE
Update discord link

### ISSUE THREAD

**Issue by njittam** [arctic-hen7/perseus#77]
Hi,

I would like to join the discord group. However the link in README.MD doesn't seem to work for me. It takes me to a page saying: "You find yourself in a strange place. You don't have access to any of the text channels, or there are none in this server."

I think the issue is that the link isn't an invite. You can create an invite that doesn't expire with: invite people -> edit link -> expire after -> never.

**Comment by lukechu10** [comment]
Ah, it's because the link is to the discord channel rather than an invite.
Here, this one should work: https://discord.com/invite/GNqWYWNTdp

**Comment by arctic-hen7** [comment]
Thanks for letting me know, I'll change this in the README.
