### ISSUE TITLE
Docs for beta still uses 0.2 as a dep

### ISSUE THREAD

**Issue by njittam** [arctic-hen7/perseus#79]
See

https://arctic-hen7.github.io/perseus/en-US/docs/0.3.x/hello-world
https://arctic-hen7.github.io/perseus/en-US/docs/next/hello-world
and
https://arctic-hen7.github.io/perseus/en-US/docs/0.3.x/second-app
https://arctic-hen7.github.io/perseus/en-US/docs/next/second-app

side note: maybe add a docs issue template to github

**Comment by arctic-hen7** [comment]
Ah, thank you very much!

**Comment by arctic-hen7** [comment]
This should now be updated on the website, and I've also added the instruction on installing the Wasm target (which was missing from previous versions of the docs).
