### ISSUE TITLE
The root path of an app should serve default language without wasm/js-enabled

### ISSUE THREAD

**Issue by adundovi** [arctic-hen7/perseus#82]
**Describe the bug**
When one uses the prescribed language settings, like:
```
    locales: {
        default: "en-US",
        other: ["fr-FR", "es-ES"]
    }
```
a default language (in this case "en-US") should be served when the root path ("/") is visited without wasm/js-enabled. For example, when web crawlers visit the site they do not execute wasm thus they don't get any content served on a deployed (exported) site making the website hidden for search engines.

**To Reproduce**
1. Use i18n example from perseus examples
2. Generate static version of the app: perseus export
3. curl http://localhost:8080

**Expected behavior**
Expect to see the content of the default language

**Screenshots**

**Environment (please complete the following information):**
 - Perseus Version: 0.3.0-beta.17
 - Sycamore Version: v0.6.3
 - OS: Linux
 - Browser: all

**Comment by arctic-hen7** [comment]
This behavior is actually intentional, and it's a prescriptive i18n design that ensures that there is no true default locale. I can certainly make it clearer in the documentation though that the default locale is only used as a fallback if the user has no matching locales set as their preferences.

Also, to my knowledge, a lot of modern crawlers do execute Wasm now, so this shouldn't be an SEO problem (it certainly hasn't been with the Perseus website, for which DuckDuckGo displayed a localized link for `en-US` based on the only link to the website at the time, an unlocalized link on the GitHub page, note that that link is now localized for convenience though).

This behavior is certainly a bit of a 'gotcha' though, so I think instructions on it should be added to the docs. Are you happy with that?

**Comment by adundovi** [comment]
Thanks @arctic-hen7 for your reply. I understood the reasoning from the documentation, however, in my case, neither Bing's nor Google's crawler are able to index my perseus test page which is basically just an extension of the second app from the documentation. I checked in the Search Console, and I only received status "excluded." I tried to add sitemap.xml, but that didn't fix the issue.

Here is a screenshot from Search Console:
![image](https://user-images.githubusercontent.com/8830248/143316250-fd692784-6a26-4499-99da-b63d21c57df3.png)

**Comment by lukechu10** [comment]
@adundovi "Excluded" just means that google will index it at some point. This is intentional and shouldn't be any different whether you use perseus or another other framework.

**Comment by adundovi** [comment]
OK, thanks for explaining. I still do see some issues with this, for example, before wasm is not fully loaded, users see a blank page which makes them think that a site is unavailable in the first moment (several users reported this to me, wasm is ~200 kb compressed), but I'll find another way to fix it.

**Comment by arctic-hen7** [comment]
That issue is tracked by #61 at the moment, and will be fixed before v0.3.0 when the next version of Sycamore is released.

**Comment by adundovi** [comment]
@arctic-hen7, I think that would cover the case when JS/Wasm is not available, and one would still be able to get some content, even if it lands on unlocalized path. Yet, after #61 is fixed, my main concern are the web crawlers and "old" browsers with no or bad JS/Wasm support. Will they recognize this kind of redirection? If yes, then everything is covered - great! If no, maybe this addition is only for really marginal cases and not worth the hassle.

**Comment by adundovi** [comment]
https://caniuse.com/mdn-html_elements_meta_http-equiv_refresh

**Comment by arctic-hen7** [comment]
I think that link shows that they will, so I'll get to work on this! it should just be a simple content injection...

**Comment by arctic-hen7** [comment]
Okay, I've just added two fallback locale redirection systems: one in JS that detects if Wasm is disabled, and if it is it'll redirect to the default locale; and the second for if both JS and Wasm are disabled, in which case it'll do the same, but with a `<meta>` tag. This is now integrated into both served and exported sites, and will be released in the next beta version.

**Comment by adundovi** [comment]
Great! Thank a lot.
