### ISSUE TITLE
Disabling optimizations for specific packages in Cargo.toml?

### ISSUE THREAD

**Issue by adundovi** [arctic-hen7/perseus#83]
**Describe the bug**
I've encountered the following [bug](https://github.com/rust-lang/rust/issues/91011) in Rust, i.e., when building a package with `perseus build` (or `serve` or `test`), the "Building your app to Wasm..." step never ends (finally being killed by the OOM killer). It only happens for the `--release` target of wasm32, not for x86_64 and wasm32 without `--release`.

A workaround for this bug is to disable optimizations for `fluent-bundle`.

How do I specify `opt-level = 0` for the `fluent-bundle` package in `Cargo.toml` so that `perseus-cli` picks it up and builds the package with the option present? I tried just putting in Cargo.toml, but it didn't work. It would be great to see in Perseus' docs how to do this...

**Environment:**
 - Perseus Version: 0.3.0-beta.17
 - Sycamore Version: 0.6
 - OS: Linux

**Comment by adundovi** [comment]
Adding
```
[profile.release.package]
fluent-bundle = { opt-level = 2 }
```
in `.perseus/Cargo.toml` works as the mentioned workaround, but I wouldn't like to modify the .perseus directory manually.

**Comment by phaleth** [comment]
As far as optimizations are concerned I'd think the `--release` flag is one of the gotchas.

I suggest dropping the `--release` flag completely as hinted here https://github.com/arctic-hen7/perseus/issues/52#issuecomment-936984297.

In case you want to avoid modifying `.perseus/` dir contents you can use the `perseus-size-opt` plugin as demonstrated here https://github.com/arctic-hen7/perseus/issues/69#issuecomment-962587245.

Also, please, next time specify at least your linux distro.

**Comment by adundovi** [comment]
Hmm, to me it looks like the `--release` flag is always on, whether I pass `--release` to build/serve/export or not.

**Comment by arctic-hen7** [comment]
@adundovi I think this should probably be an issue on the size optimizations plugin, as Perseus itself is agnostic about how you perform optimizations. I could also create another plugin, but I think the simplest thing is just to patch the size optimizations plugin to perform that workaround.

**Comment by adundovi** [comment]
@arctic-hen7 thanks for the feedback. Are the perseus plugins listed somewhere?

**Comment by arctic-hen7** [comment]
Yes! See the Plugins section on the website. (At the moment there's only one...)

**Comment by arctic-hen7** [comment]
Okay, the size optimizations plugin now has this patch inbuilt unless the `default_2018()` function is used (seeing as this only seems to affect Rust 2021). @adundovi I would recommend using v0.1.4 of that plugin to perform your size optimizations for you, and this error should then no longer be a problem! Please let me know if that's not the case and I'll reopen this issue.

**Comment by adundovi** [comment]
Hi @arctic-hen7, thank you for the plugin and for including the workaround in the plugin by default.

May I just note that I have to change the prescribed line on how to use the plugin into:
```rust
plugins: Plugins::new().plugin(|| perseus_size_opt(), SizeOpts::default())
```
since otherwise, I cannot compile:
```
plugins: Plugins::new().plugin(perseus_size_opt(), SizeOpts::default() )
                        expected an `Fn<()>` closure, found `Plugin<_, SizeOpts>`
```

**Comment by arctic-hen7** [comment]
Ah! Yes, sorry, that's an issue kn the docs for the plugin. You don't need a closure, just use `perseus_size_opt` without the brackets. There's an example [here](https://www.github.com/arctic-hen7/perseus/tree/main/website%2Fsrc%2Flib.rs).

**Comment by adundovi** [comment]
Eh, yes, you're right, and it makes perfect sense. (me embarrassed)

**Comment by adundovi** [comment]
Hmm, does not work after `perseus clean`.

**Comment by arctic-hen7** [comment]
Have you run `perseus tinker` afterward?

**Comment by adundovi** [comment]
No, I forgot. Afterward, it worked. Thank you.

**Comment by arctic-hen7** [comment]
No problem!
