### ISSUE TITLE
"no prebuilt wasm-opt" error on M1 MacBook Pro

### ISSUE THREAD

**Issue by dolphingarlic** [arctic-hen7/perseus#89]
**Describe the bug**
When I try to run [the hello world example from the docs](https://arctic-hen7.github.io/perseus/en-US/docs/0.2.x/hello-world), I get the following error:

```
Error: no prebuilt wasm-opt binaries are available for this platform: Unrecognized target!
To disable `wasm-opt`, add `wasm-opt = false` to your package metadata in your `Cargo.toml`.
```

Even when I add

```
[package.metadata.wasm-pack.profile.release]
wasm-opt = false
```

to `Cargo.toml` like [this GitHub issue](https://github.com/rustwasm/wasm-pack/issues/913) says I should, it still gives me the same error.

**To Reproduce**
1. Follow the hello world example on an M1 MacBook Pro.
2. Disable wasm-opt in `Cargo.toml`.
3. Run `perseus serve`.

**Expected behavior**
The app should run without errors.

**Environment (please complete the following information):**
 - Perseus Version: v0.2.0
 - Sycamore Version: v0.6.0
 - OS: macOS Monterey
 - Browser: Chrome
 - Browser Version: 96.0.4664.93

**Comment by arctic-hen7** [comment]
Hmm okay, thanks for letting me know about this. Could you try adding that fix to `.perseus/Cargo.toml` as well? I suspect that might work...

**Comment by dolphingarlic** [comment]
> Could you try adding that fix to .perseus/Cargo.toml as well? I suspect that might work...

This works - thanks!

I don't really want to mess around with Rust, but it seems [this PR](https://github.com/rustwasm/wasm-pack/pull/1088) should (hopefully) fix this.

**Comment by arctic-hen7** [comment]
Great! I'll get to work on creating a plugin to automate this process so you don't have to modify `.perseus/` in future. Then I'll add that to the docs as a common pitfall until that PR goes through. Given I don't have an ARM system easily to hand and architecutre emulation is annoying for something this tiny, would you mind testing it once it's ready?
