### ISSUE TITLE
How to use `http request` or `async/await` in `perseus`?

### ISSUE THREAD

**Issue by rieval** [arctic-hen7/perseus#91]
Hi!

I'm trying to write a demo that gets data from the `Actix web` server based on the `GraphQL` API.

I am not familiar with `Rust` and `wasm`, so I have read the docs for `perseus`, but I did not find anything about `http request`(e.g. `GET` / `POST` method).

Is it possible to add an example on how to use `http request`?

BTW, does `perseus` support `async/await`?

Edited:

I found two Rust libraries about using `http request` in `wasm`, but I'm not sure if I can use it in `perseus`:

[reqwest](https://github.com/seanmonstar/reqwest) / [reqwasm](https://github.com/hamza1311/reqwasm)

Looking forward to your reply, thanks!

**Comment by arctic-hen7** [comment]
With v0.3.x, you should be able to communicate with a server by following [this page](https://arctic-hen7.github.io/perseus/en-US/docs/0.3.x/server-communication) in the docs. It's not very specific, but either of those libraries should work I think. If you want to get data at build time for example, you'd use [the build state strategy](https://arctic-hen7.github.io/perseus/en-US/docs/0.3.x/strategies/build-state), which takes an asynchronous function, in which you should be able to do what you want.

**Comment by arctic-hen7** [comment]
By the way, questions like these are better as discussions or questions on the Discord server in future.

**Comment by rieval** [comment]
> With v0.3.x, you should be able to communicate with a server by following [this page](https://arctic-hen7.github.io/perseus/en-US/docs/0.3.x/server-communication) in the docs. It's not very specific, but either of those libraries should work I think. If you want to get data at build time for example, you'd use [the build state strategy](https://arctic-hen7.github.io/perseus/en-US/docs/0.3.x/strategies/build-state), which takes an asynchronous function, in which you should be able to do what you want.

Sorry, it's my fault, I didn't read the code in the documentation carefully.

> By the way, questions like these are better as discussions or questions on the Discord server in future.

Sorry again. I'm not in the habit of using Discord.

For some reason I can't access Discord server directly, but I will make changes to it.

Thank you for your reply!

**Comment by arctic-hen7** [comment]
No problem! You can also use GitHub discussions if that's easier.
